import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "@/styles/style.css";
import "@/styles/other.css";
import Footer from "@/components/footer";
import Provider from "./provider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={montserrat.className}>
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
